### ISSUE TITLE
Ctrl-C to stop server does not work

### ISSUE THREAD

**Issue by franknieu** [facebookresearch/aepsych#13]
In my anaconda environment on Windows 10, ctrl-c does not stop the AEPsych server. Instead, I need to close the anaconda prompt, forcing me to restart everything from scratch.

**Comment by CamilleFradet** [comment]
Hey @franknieu ,

I had the same issue and found out the solution is to use ctrl+break instead of ctrl+c.

Hope this works for you :)

**Comment by mshvartsman** [comment]
Thanks for the catch -- I'll add changing the message on windows to our backlog, and keep this issue open to track until we've done it.
